### PR TITLE
Test for $#,###.00; passing and #.00$; failing

### PR DESCRIPTION
**Pull request by Dutchgoose**
Just adding some test cases to go along with this PR: #33606 in helltool. The one for `$#,###.00;` passes and `#.00$;` fails.

### CODE REVIEW

**Comment by Dutchgoose** [comment]
screen shot 2017-11-13 at 3 16 26 pm

**Comment by n8agrin** [comment]
So now there is one failing test?

**Comment by n8agrin** [comment]
I pulled this branch and didn't get any failing tests. I'm confused.

**Comment by Dutchgoose** [comment]
I merged with master and it looks to work. I pushed up again. Try this one?

**Comment by n8agrin** [comment]
Ok, this works for me now. Feels strange to have a failing test, but at least this is honest.

**Review by n8agrin — APPROVED** [review]

**Pull request merged**
